#pragma once

#define CANVAS_WIDTH  560
#define CANVAS_HEIGHT 560
#define WIDTH         CANVAS_WIDTH + 300
#define HEIGHT        CANVAS_HEIGHT
#define SCREEN        WIDTH* HEIGHT
#define CANVAS_AREA   CANVAS_WIDTH* CANVAS_HEIGHT